kind: ConfigMap
apiVersion: v1
metadata:
  name: httpd-var-secure
data:
  index.html: |-
    <!DOCTYPE html>
    <html>
    <head>
    <title>A secured resource</title>
    </head>
    <body>
    This page has been secured by shibboleth
    </body>
    </html>
