dependencies:
  - name: jupyterhub
    version: 0.9-b63f5c9
    repository: https://jupyterhub.github.io/helm-chart
  - name: efs-provisioner
    version: 0.7.0
    repository: https://kubernetes-charts.storage.googleapis.com/
