dependencies:
  - name: jupyterhub
    version: 0.9.1
    repository: https://jupyterhub.github.io/helm-chart
  - name: efs-provisioner
    version: 0.13.0
    repository: https://kubernetes-charts.storage.googleapis.com/
