dependencies:
  - name: jupyterhub
    version: 0.8.2
    repository: https://jupyterhub.github.io/helm-chart
  - name: nginx-ingress
    version: 1.11.3
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: cert-manager
    version: v0.9.0
    repository: https://charts.jetstack.io
